### ISSUE TITLE
vertx-jdbc C3P0DataSourceProvider not support config ```preferredTestQuery```

### ISSUE THREAD

**Issue by ordiy** [vert-x3/vertx-jdbc-client#134]
### Version

* vert.x core: 3.4.1
* vert.x jdbc-client:3.4.1
* jdbc driver: jdbc4
* RDBMS: mysql 5.7

### General info

* What is your jdbc driver
* What is your RDBMS server
* What is your connection string (no user/passwords please!)
my mysql connection config json:
```
{
  "url": "jdbc:mysql://xxxxxxxxxx:3306/xxxx_test?autoReconnect=true",
  "driver_class":"com.mysql.jdbc.Driver",
  "max_pool_size": 50,
  "initial_pool_size": 10,
  "min_pool_size": 10,
  "user": "xxxxxx",
  "password": "xxxx",
  "maxIdleTime":3600,
  "idleConnectionTestPeriod":30,
  "testConnectionOnCheckout":false,
  "testConnectionOnCheckin":true,
"preferredTestQuery":SELECT 1
}
```

### Context
as  io.vertx.ext.jdbc.spi.impl.VertxFactoryLoader not support config ```preferredTestQuery```, my application had an exception:
```
2018-05-21 20:15:52.605 [vert.x-eventloop-thread-12] ERROR c.j.d.p.s.AuthCacheService- queryDbPermissionInfo failed,will retry 1 time,cause:
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 92,618,957 milliseconds ago.  The last packet sent successfully to the server was 92,618,958 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
	at sun.reflect.GeneratedConstructorAccessor74.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1074)
	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3313)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1940)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2109)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2643)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2077)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1356)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.execute(NewProxyPreparedStatement.java:67)
	at io.vertx.ext.jdbc.impl.actions.JDBCQuery.execute(JDBCQuery.java:52)
	at io.vertx.ext.jdbc.impl.actions.JDBCQuery.execute(JDBCQuery.java:31)
	at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.handle(AbstractJDBCAction.java:58)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:271)
	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3294)
	... 14 common frames omitted

```
I think this is framework bug.

**Comment by tsegismont** [comment]
First I would not use `autoReconnect=true` in the connection url, especially if connection is managed in a pool. See the [connector-j documentation](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-configuration-properties.html) on this connection property.

Then you can set any c3p0 property by adding a `c3p0.properties` file to the classpath, as indicated in the [documentation](https://vertx.io/docs/vertx-jdbc-client/java/#_configuration).

**Comment by FreeTymeKiyan** [comment]
@tsegismont I tried to add a c3p0.properties file to classpath and run my vertx app like this:
`java -jar build/libs/apas-be-0.1.0-fat.jar -cp "build/resources/main/*"`

But when I checked the log c3p0 still didn't pick up the properties I added. 

Properties file 
```
acquireIncrement=1
testConnectionOnCheckin=true
testConnectionOnCheckOut=false
idleConnectionTestPeriod=300
maxIdleTimeExcessConnections=240
preferredTestQuery=SELECT 1
```

Log 
```
Reading VM config for path list /com/mchange/v2/log/default-mchange-log.properties, /mchange-commons.properties, /c3p0.properties, hocon:/reference,/application,/c3p0,/, /mchange-log.properties, /
The configuration file for resource identifier '/mchange-commons.properties' could not be found. Skipping.
The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.
The configuration file for resource identifier '/mchange-log.properties' could not be found. Skipping.
The configuration file for resource identifier '/mchange-commons.properties' could not be found. Skipping.
The configuration file for resource identifier '/mchange-log.properties' could not be found. Skipping.
The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.
Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
MBean: com.mchange.v2.c3p0:type=PooledDataSource,identityToken=2rvxtwa0tinewz7svfoc|16fb958f,name=2rvxtwa0tinewz7svfoc|16fb958f registered.
MBean: com.mchange.v2.c3p0:type=PooledDataSource,identityToken=2rvxtwa0tinewz7svfoc|16fb958f,name=2rvxtwa0tinewz7svfoc|16fb958f unregistered, in order to be reregistered after update.
MBean: com.mchange.v2.c3p0:type=PooledDataSource,identityToken=2rvxtwa0tinewz7svfoc|16fb958f,name=2rvxtwa0tinewz7svfoc|16fb958f registered.
Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 2rvxtwa0tinewz7svfoc|16fb958f, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> com.mysql.cj.jdbc.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 2rvxtwa0tinewz7svfoc|16fb958f, idleConnectionTestPeriod -> 0, initialPoolSize -> 3, jdbcUrl -> jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {password=******, user=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
The configuration file for resource identifier '/mchange-commons.properties' could not be found. Skipping.
The configuration file for resource identifier '/mchange-log.properties' could not be found. Skipping.
The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.
com.mchange.v2.resourcepool.BasicResourcePool@b34b04a config: [start -> 3; min -> 3; max -> 15; inc -> 3; num_acq_attempts -> 30; acq_attempt_delay -> 1000; check_idle_resources_delay -> 0; max_resource_age -> 0; max_idle_time -> 0; excess_max_idle_time -> 0; destroy_unreturned_resc_time -> 0; expiration_enforcement_delay -> 0; break_on_acquisition_failure -> false; debug_store_checkout_exceptions -> false; force_synchronous_checkins -> false]
```

Could you kindly share why?

**Comment by FreeTymeKiyan** [comment]
@tsegismont I realized that as the file `c3p0.properties` is put under resources directory, when I generate the fat jar, it's included already.  I verified that by unzipping the fat jar. Simply run `java -jar the-fat.jar` should pick up the properties right? How come the properties are still not picked up?

**Comment by FreeTymeKiyan** [comment]
Alright. I compared my new log file with the old ones before I added the properties file. It seems that the file is found, but the properties are not set for some reason. I revisited [the c3p0 docs](https://www.mchange.com/projects/c3p0/#c3p0_properties), and noticed that all properties are prefixed with `c3p0.`. 

So the exact way to add those c3p0 configurations is: 
1. add a file named `c3p0.properties` under resources in your project. Note that each property name is prefixed with `c3p0.`
2. generate a fat jar 
3. `java -jar your-fat-jar.jar`

Now you should be able to see the new properties in the log.
