### ISSUE TITLE
Exception when execute stored procedure with cursor output parameter

### ISSUE THREAD

**Issue by dat91** [vert-x3/vertx-jdbc-client#135]
### Version

* vert.x core: 3.5.1
* vert.x jdbc-client: 3.5.1
* jdbc driver: oracle.jdbc.pool.OracleDataSource
* RDBMS: Oracle Database 12.2.0.1

### General info

* What is your jdbc driver: oracle.jdbc.pool.OracleDataSource
* What is your RDBMS server: Oracle Database 12.2.0.1
* What is your connection string (no user/passwords please!): `jdbc:oracle:thin:@//${host}:${port}/${service}`

### Context
I have a simple stored procedure like this:
```sql
CREATE OR REPLACE PROCEDURE TEST_OUT(p_out OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN p_out FOR SELECT 'HELLO' FROM DUAL;
  END ;
```
Then I invoke from the JDBC Client
``` java
JsonArray out = new JsonArray().add(OracleTypes.CURSOR);
client.callWithParams("{call TEST_OUT(?)}", null, out, resultSetHandler -> {
            if (resultSetHandler.failed()) {
                resultSetHandler.cause().printStackTrace();
            }
        });
```
Output:
```
java.lang.IllegalStateException: Illegal type in JsonObject: class io.vertx.ext.sql.ResultSet
	at io.vertx.core.json.Json.checkAndCopy(Json.java:210)
	at io.vertx.core.json.JsonArray.add(JsonArray.java:439)
	at io.vertx.ext.jdbc.impl.actions.JDBCCallable.convertOutputs(JDBCCallable.java:100)
	at io.vertx.ext.jdbc.impl.actions.JDBCCallable.execute(JDBCCallable.java:80)
	at io.vertx.ext.jdbc.impl.actions.JDBCCallable.execute(JDBCCallable.java:31)
	at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.handle(AbstractJDBCAction.java:58)
	at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.lambda$execute$0(AbstractJDBCAction.java:66)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```
### Solution
I looked at JDBCCallable and this statement: 
``` java
result.add(helper.asList((ResultSet)value));
``` 
will always throw exception since Json cannot accept value of type ResultSet.

As a quick fix, I changed it to: 
``` java
result.add(helper.asList((ResultSet) value).toJson());
```
The exception is gone and I can get the output by json processing, or reconstruct the ResultSet from json. But I think there's should be a better solution, can we take a look at that?

**Comment by tsegismont** [comment]
@dat91 your fix looks good to me.

 @pmlopes I wonder how this could work actually. Thoughts? It seems `ResultSet` as an `OUT` param was introduced in #36 . I think it's important as it's the only for Oracle users to get query results out of a stored procedure.

**Comment by tunovic** [comment]
Any idea when this issue will be resolved? Using Vert.x 3.8.1 with Hikari and Oracle driver.
