### ISSUE TITLE
get byte[] from JDBC for GZIP decompression

### ISSUE THREAD

**Issue by MeiyappanKannappa** [vert-x3/vertx-jdbc-client#138]
HI I have compressed data as byte[], stored in DB table column. I need to get the byte[] and decompress it. But there is no direct method to get data as byte[] in vert.x jdbc. I tried using getBinary(0) , but it throws me below exception

java.lang.IllegalArgumentException: Illegal base64 character 1f
at java.util.Base64$Decoder.decode0(Base64.java:714)
at java.util.Base64$Decoder.decode(Base64.java:526)
at java.util.Base64$Decoder.decode(Base64.java:549)
at io.vertx.core.json.JsonArray.getBinary(JsonArray.java:222)
at com.example.test.WebVerticle.lambda$null$3(WebVerticle.java:138)
at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:81)
at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:294)
at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)

The problem is the binary data are stored in table as historical records, and by other services.
Can anyone please help me out to decompress byte[] stored in DB.
### Version

* vert.x core: 3.5
* vert.x jdbc-client:3.5
* jdbc driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
* RDBMS: SQL Server

**Comment by tsegismont** [comment]
What's the DB column definition?

**Comment by MeiyappanKannappa** [comment]
hi the column in DB is "text" data type.

**Comment by tsegismont** [comment]
Is the data encoded with base64?

**Comment by MeiyappanKannappa** [comment]
It is not encoded with Base64. The output of GZIPCompression is stored as such in to the table.

**Comment by tsegismont** [comment]
I'm not sure what the SQLServer driver does when you store an array of bytes in a text column. In any case, [`JsonArray.getBytes(int)`](https://vertx.io/docs/apidocs/io/vertx/core/json/JsonArray.html#getBinary-int-) expects a base64 string (JSON spec has no notion of binary). I would recommend to convert the column data to base64 in your SQL queries.

**Comment by tsegismont** [comment]
I did not mean converting the stored data, I meant converting the stored data from text to base 64 on the fly when executing your queries.
