### ISSUE TITLE
Deadlock unhandled exception

### ISSUE THREAD

**Issue by kostya05983** [vert-x3/vertx-jdbc-client#165]
### Version

* vert.x core: 3.7.0
* vert.x jdbc-client: 3.7.0
* jdbc driver: mysql-connector-java  5.1.38
* RDBMS: mysql innodb 

### General info

* What is your jdbc driver 
* What is your RDBMS server 
mysql innodb 5.6
* What is your connection string (no user/passwords please!)
jdbc:mysql://10.25.96.65/radius?useUnicode=true&characterEncoding=utf8&relaxAutoCommit=true&connectTimeout=5000&autoReconnect=true
### Context
We have to update on one table with rxUpdateWithParams, and sometimes catch a deadlock exception, looks
```
2019-07-05T15:09:31,635 [vert.x-eventloop-thread-3] ERROR ContextImpl ?.(line:). Unhandled exception
rx.exceptions.OnErrorNotImplementedException: Lock wait timeout exceeded; try restarting transaction
        at rx.functions.Actions$NotImplemented.call(Actions.java:576) ~[.jar:1.13-103 (20190701-1533)]
        at rx.functions.Actions$NotImplemented.call(Actions.java:572) ~[.jar:1.13-103 (20190701-1533)]
        at rx.Single$11.onError(Single.java:1794) ~[.jar:1.13-103 (20190701-1533)]
        at io.vertx.rx.java.SingleOnSubscribeAdapter.lambda$call$0(SingleOnSubscribeAdapter.java:33) ~[.jar:1.13-103 (20190701-1533)]
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:284) ~[.jar:1.13-103 (20190701-1533)]
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320) ~[.jar:1.13-103 (20190701-1533)]
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[.jar:1.13-103 (20190701-1533)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[.jar:1.13-103 (20190701-1533)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[.jar:1.13-103 (20190701-1533)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) ~[eltex-pcrf.jar:1.13-103 (20190701-1533)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[.jar:1.13-103 (20190701-1533)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[.jar:1.13-103 (20190701-1533)]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
        at sun.reflect.GeneratedConstructorAccessor86.newInstance(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[.jar:1.13-103 (20190701-1533)]
        at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[.jar:1.13-103 (20190701-1533)]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946) ~[.jar:1.13-103 (20190701-1533)]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878) ~[.jar:1.13-103 (20190701-1533)]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814) ~[.jar:1.13-103 (20190701-1533)]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478) ~[.jar:1.13-103 (20190701-1533)]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625) ~[.jar:1.13-103 (20190701-1533)]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551) ~[.jar:1.13-103 (20190701-1533)]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861) ~[.jar:1.13-103 (20190701-1533)]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073) ~[.jar:1.13-103 (20190701-1533)]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009) ~[jar:1.13-103 (20190701-1533)]
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094) ~[.jar:1.13-103 (20190701-1533)]
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994) ~[.jar:1.13-103 (20190701-1533)]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[.jar:1.13-103 (20190701-1533)]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[.jar:1.13-103 (20190701-1533)]
        at io.vertx.ext.jdbc.impl.actions.JDBCUpdate.execute(JDBCUpdate.java:92) ~[.jar:1.13-103 (20190701-1533)]
        at io.vertx.ext.jdbc.impl.actions.JDBCUpdate.execute(JDBCUpdate.java:31) ~[.jar:1.13-103 (20190701-1533)]
        at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.handle(AbstractJDBCAction.java:58) ~[.jar:1.13-103 (20190701-1533)]
        at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.lambda$execute$0(AbstractJDBCAction.java:66) ~[.jar:1.13-103 (20190701-1533)]
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:272) ~[.jar:1.13-103 (20190701-1533)]
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[.jar:1.13-103 (20190701-1533)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_121]
```

### Do you have a reproducer?

Unfortunately, we face with it only on production.

### Extra

We use hazelcast as cluster manager an have three nodes of our server, version of hazelcast 3.11.1.
We want to handle it by driver of vertx, because now it is unhanded and freeze the work of vertx. Or any useful advices to avoid deadlock welcome.

**Comment by tsegismont** [comment]
Looking at the cause:

```
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
```

It seems your query needs to acquire a database lock and sometimes cannot do it in a timely manner. This may happen for example if you another transaction holds the database lock for a long time.

Reach out to MySQL user groups if you need help for troubleshooting this kind of issue.

**Comment by kostya05983** [comment]
Hello, @tsegismont thank you for response, but can a vertx-jdbc-driver handle such exception? Or is it impossible? I just want to catch it onError, but I can't :(
something like this:
`
mysql.rxUpdateWithParams("My_statement", JsonArray().add).subscribe({

}, {
//I want an exception there
})
`
 If it's impossible to handle from vert.x driver, you may close issue.
`2019-07-05T15:09:31,635 [vert.x-eventloop-thread-3] ERROR ContextImpl ?.(line:). Unhandled exception`
Best wishes:)

**Comment by tsegismont** [comment]
@kostya05983 the top lines of the stack trace show this

```
2019-07-05T15:09:31,635 [vert.x-eventloop-thread-3] ERROR ContextImpl ?.(line:). Unhandled exception
rx.exceptions.OnErrorNotImplementedException: Lock wait timeout exceeded; try restarting transaction
        at rx.functions.Actions$NotImplemented.call(Actions.java:576) ~[.jar:1.13-103 (20190701-1533)]
        at rx.functions.Actions$NotImplemented.call(Actions.java:572) ~[.jar:1.13-103 (20190701-1533)]
        at rx.Single$11.onError(Single.java:1794) ~[.jar:1.13-103 (20190701-1533)]
        at io.vertx.rx.java.SingleOnSubscribeAdapter.lambda$call$0(SingleOnSubscribeAdapter.java:33) ~[.jar:1.13-103 (20190701-1533)]
```

It seems `SingleOnSubscribeAdapter` does invoke the subscriber `onError` method. But `OnErrorNotImplementedException` indicates the subscription was created with:

```java
single.subscribe(r -> { /* do something with result */})
```

Which internally does:

```java
    public final Subscription subscribe() {
        return subscribe(Actions.empty(), Actions.errorNotImplemented());
    }
```

Can you double check that an error handler is defined at subscription time? Thank you.
