### ISSUE TITLE
JDBCQuery-execution triggers blocked thread checker

### ISSUE THREAD

**Issue by ChristophGr** [vert-x3/vertx-jdbc-client#169]
### Version

* vert.x core: 3.8.0
* vert.x jdbc-client: 3.8.0
* jdbc driver: oracle 12.1.0.2
* RDBMS: Oracle SE 12.1.0.2

### General info

* What is your jdbc driver
Oracle 12c release 1 (12.1.0.2)
* What is your RDBMS server
Oracle SE 12.1.0.2
* What is your connection string (no user/passwords please!)
jdbc:oracle:thin:@//localhost:1521/ORCLPDB1

### Context

```
Aug 16, 2019 11:10:14 AM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-worker-thread-4,5,main]=Thread[vert.x-worker-thread-4,5,main] has been blocked for 61618 ms, time limit is 60000 ms
io.vertx.core.VertxException: Thread blocked
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at oracle.net.ns.Packet.receive(Packet.java:311)
	at oracle.net.ns.DataPacket.receive(DataPacket.java:105)
	at oracle.net.ns.NetInputStream.getNextPacket(NetInputStream.java:305)
	at oracle.net.ns.NetInputStream.read(NetInputStream.java:249)
	at oracle.net.ns.NetInputStream.read(NetInputStream.java:171)
	at oracle.net.ns.NetInputStream.read(NetInputStream.java:89)
	at oracle.jdbc.driver.T4CSocketInputStreamWrapper.readNextPacket(T4CSocketInputStreamWrapper.java:123)
	at oracle.jdbc.driver.T4CSocketInputStreamWrapper.readLongMSB(T4CSocketInputStreamWrapper.java:198)
	at oracle.jdbc.driver.T4CMAREngineStream.buffer2Value(T4CMAREngineStream.java:851)
	at oracle.jdbc.driver.T4CMAREngineStream.unmarshalUB4(T4CMAREngineStream.java:538)
	at oracle.jdbc.driver.T4CClobAccessor.unmarshalPrefetchData(T4CClobAccessor.java:231)
	at oracle.jdbc.driver.T4CClobAccessor.unmarshalBytes(T4CClobAccessor.java:213)
	at oracle.jdbc.driver.T4CClobAccessor.unmarshalOneRow(T4CClobAccessor.java:179)
	at oracle.jdbc.driver.T4CTTIrxd.unmarshal(T4CTTIrxd.java:1474)
	at oracle.jdbc.driver.T4CTTIrxd.unmarshal(T4CTTIrxd.java:1282)
	at oracle.jdbc.driver.T4C8Oall.readRXD(T4C8Oall.java:851)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:448)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:225)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:53)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:957)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1111)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:4798)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:4901)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1385)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.execute(NewProxyPreparedStatement.java:67)
	at io.vertx.ext.jdbc.impl.actions.JDBCQuery.execute(JDBCQuery.java:48)
	at io.vertx.ext.jdbc.impl.actions.JDBCQuery.execute(JDBCQuery.java:30)
	at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.handle(AbstractJDBCAction.java:59)
	at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.lambda$execute$0(AbstractJDBCAction.java:67)
	at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction$$Lambda$441/1348657678.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.ContextImpl$$Lambda$442/985388421.run(Unknown Source)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at io.vertx.core.impl.TaskQueue$$Lambda$327/343563528.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

### Steps to reproduce

1.  connection.rxQuery(someLongRunningSQLQuery)

### Extra

* The statement I used when I encountered the exception actually took around 80 seconds to complete.

**Comment by pmlopes** [comment]
The new sql-client api that replaced the deprecated one, does handle without issues blocking queries.
