### ISSUE TITLE
Oracle insert error

### ISSUE THREAD

**Issue by zcx2001** [vert-x3/vertx-jdbc-client#17]
JDBCUpdate.java  in  keys.add(convertSqlValue(rs.getObject(1)));

java.lang.IllegalStateException: Illegal type in JsonObject: class oracle.sql.ROWID
	at io.vertx.core.json.Json.checkAndCopy(Json.java:116)
	at io.vertx.core.json.JsonArray.add(JsonArray.java:396)
	at io.vertx.ext.jdbc.impl.actions.JDBCUpdate.executeStatement(JDBCUpdate.java:53)
	at io.vertx.ext.jdbc.impl.actions.JDBCUpdate.executeStatement(JDBCUpdate.java:33)
	at io.vertx.ext.jdbc.impl.actions.AbstractJDBCStatement.execute(AbstractJDBCStatement.java:44)

**Comment by zcx2001** [comment]
convertSqlValue not cast oracle.sql.ROWID @pmlopes

**Comment by pmlopes** [comment]
No, because that is a oracle specific type so it falls in the last attempt to cast as a `toString()`

**Comment by zcx2001** [comment]
But I think we should solve the problem of throwing exception in io.vertx.ext.jdbc.impl.actions.JDBCUpdate executeStatement

If you can't toString, capture exceptions and return null
