### ISSUE TITLE
rxQuery breaks between 4.0.0-milestone3 and 4.0.0-milestone4.

### ISSUE THREAD

**Issue by jonathon-eastman** [vert-x3/vertx-jdbc-client#179]
### Version

4.0.0-milestone4

### Context

I have a simple RxJava2 query that I have been using for awhile.  I updated to the latest maven release (4.0.0-milestone4) and I now get this error stacktrace.

jdbc driver: oracle.jdbc.OracleDriver
jdbc url: jdbc:oracle:thin:@<MYHOST>:1521:<MYDB>
oracle jdbc jar: ojdbc8
oracle jdbc version: 19.3.0.0

> io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.UnsupportedOperationException
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:65)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
	at io.reactivex.internal.operators.single.SingleDoFinally$DoFinallyObserver.onSuccess(SingleDoFinally.java:73)
	at io.reactivex.internal.operators.single.SingleDoAfterTerminate$DoAfterTerminateObserver.onSuccess(SingleDoAfterTerminate.java:71)
	at io.reactivex.internal.operators.single.SingleDoOnError$DoOnError.onSuccess(SingleDoOnError.java:52)
	at io.vertx.reactivex.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:49)
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:183)
	at io.vertx.core.impl.EventLoopContext.lambda$execute$0(EventLoopContext.java:42)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.UnsupportedOperationException
	at io.vertx.core.json.jackson.JacksonCodec.encodeJson(JacksonCodec.java:291)
	at io.vertx.core.json.jackson.JacksonCodec.encodeJson(JacksonCodec.java:268)
	at io.vertx.core.json.jackson.JacksonCodec.encodeJson(JacksonCodec.java:274)
	at io.vertx.core.json.jackson.JacksonCodec.toString(JacksonCodec.java:91)
	at io.vertx.core.json.JsonArray.encodePrettily(JsonArray.java:502)
	at awesome.jdbc_bug.App.lambda$5(App.java:22)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	... 15 more
Exception in thread "vert.x-eventloop-thread-0" io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.UnsupportedOperationException
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:65)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
	at io.reactivex.internal.operators.single.SingleDoFinally$DoFinallyObserver.onSuccess(SingleDoFinally.java:73)
	at io.reactivex.internal.operators.single.SingleDoAfterTerminate$DoAfterTerminateObserver.onSuccess(SingleDoAfterTerminate.java:71)
	at io.reactivex.internal.operators.single.SingleDoOnError$DoOnError.onSuccess(SingleDoOnError.java:52)
	at io.vertx.reactivex.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:49)
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:183)
	at io.vertx.core.impl.EventLoopContext.lambda$execute$0(EventLoopContext.java:42)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.UnsupportedOperationException
	at io.vertx.core.json.jackson.JacksonCodec.encodeJson(JacksonCodec.java:291)
	at io.vertx.core.json.jackson.JacksonCodec.encodeJson(JacksonCodec.java:268)
	at io.vertx.core.json.jackson.JacksonCodec.encodeJson(JacksonCodec.java:274)
	at io.vertx.core.json.jackson.JacksonCodec.toString(JacksonCodec.java:91)
	at io.vertx.core.json.JsonArray.encodePrettily(JsonArray.java:502)
	at awesome.jdbc_bug.App.lambda$5(App.java:22)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	... 15 more

### Do you have a reproducer?

[github reproducer](https://github.com/jonathon-eastman/jdbc-bug)

### Steps to reproduce

1. really i just run a simple query

Here is sample code which is also in github:

`

		
		JDBCClient oracle = JDBCClient.createShared(Vertx.vertx(), JDBC_CONFIG);
		
		oracle.rxGetConnection().flatMap(conn ->  conn.setOptions(new SQLOptions())
			.rxQuery("SELECT * FROM <MYTABLE>")
			.doOnError(err -> System.out.println(err))
			.doAfterTerminate(conn::close)
			.doFinally(conn::close)
		).map(resultSet -> resultSet.toJson().getJsonArray("rows"))
		.subscribe(jsonArray -> System.out.println(jsonArray.encodePrettily()));
`

### Extra

* Running MacOS with Java11 but maven project is run as java8.

**Comment by vietj** [comment]
thanks for the feedback @jonathon-eastman for the reproducer it will help for sure

**Comment by tsegismont** [comment]
At the bottom of the stacktrace there is:

```
Caused by: java.lang.UnsupportedOperationException
at io.vertx.core.json.jackson.JacksonCodec.encodeJson(JacksonCodec.java:291)
at io.vertx.core.json.jackson.JacksonCodec.encodeJson(JacksonCodec.java:268)
at io.vertx.core.json.jackson.JacksonCodec.encodeJson(JacksonCodec.java:274)
at io.vertx.core.json.jackson.JacksonCodec.toString(JacksonCodec.java:91)
at io.vertx.core.json.JsonArray.encodePrettily(JsonArray.java:502)
at awesome.jdbc_bug.App.lambda$5(App.java:22)
```

It seems that the JSON object contains a Java `Number` that was not supported in `milestone4`.
I couldn't say what it is, as the reproducer project misses the database table description.
But in Vert.x Core master branch, a few types have been added recently: `Byte`, `BigDecimal` and `BigInteger`.

Can you try your project with a Vert.x core master build?

**Comment by tsegismont** [comment]
In other words, I don't believe this is a regression in the JDBC Client or the Rxified API.

**Comment by tsegismont** [comment]
@jonathon-eastman please try a master build and reopen if you still have issues. Thanks
