### ISSUE TITLE
NullPointerException with db2 prepared sql

### ISSUE THREAD

**Issue by rainmanhhh** [vert-x3/vertx-jdbc-client#215]
### Questions
code is like
```
preparedQuery(sql).execute(...)
```
and it reports NPE
```
java.lang.NullPointerException: Cannot invoke "java.sql.ResultSetMetaData.getColumnCount()" because "metaData" is null
	at io.vertx.jdbcclient.impl.actions.JDBCQueryAction.decodeReturnedKeys(JDBCQueryAction.java:183) ~[vertx-jdbc-client-4.0.2.jar:4.0.2]
	at io.vertx.jdbcclient.impl.actions.JDBCQueryAction.decode(JDBCQueryAction.java:59) ~[vertx-jdbc-client-4.0.2.jar:4.0.2]
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:69) ~[vertx-jdbc-client-4.0.2.jar:4.0.2]
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:39) ~[vertx-jdbc-client-4.0.2.jar:4.0.2]
```
same sql works fine with mysql

### Version

4.0.2

### Extra
sugguest to add null check for generatedKeys metaData (JDBCQueryAction line 182~183) because some jdbc drivers return generatedKeys even if it's not a insert statement(but metaData of the resultSet is null)

**Comment by pmlopes** [comment]
Null check was introduced in 4.1.0
