### ISSUE TITLE
[Array|String]IndexOutOfBoundsException when executing prepared queries in parallel using JDBCPool together with MariaDB Java Client

### ISSUE THREAD

**Issue by riemenschneider** [vert-x3/vertx-jdbc-client#221]
### Version

4.0.3

### Context

I am using Vert.x 4.0.3 Sql Client API for accessing a MySQL database (tested with 8.0.16, 5.7.26 and 5.6.50) via the MariaDB Java Client (2.7.2). When executing prepared queries in parallel I am encountering [Array|String]IndexOutOfBoundsExceptions that are thrown when Vert.x ``JDBCClient`` reads the column labels using the ``ResultSetMetaData`` object returned by the MariaDB Java Client.
```
java.lang.ArrayIndexOutOfBoundsException: 37
	at org.mariadb.jdbc.internal.com.read.Buffer.getLengthEncodedNumeric(Buffer.java:271)
	at org.mariadb.jdbc.internal.com.read.Buffer.readStringLengthEncoded(Buffer.java:122)
	at org.mariadb.jdbc.internal.com.read.resultset.ColumnDefinition.getString(ColumnDefinition.java:227)
	at org.mariadb.jdbc.internal.com.read.resultset.ColumnDefinition.getName(ColumnDefinition.java:243)
	at org.mariadb.jdbc.MariaDbResultSetMetaData.getColumnLabel(MariaDbResultSetMetaData.java:154)
	at io.vertx.jdbcclient.impl.actions.JDBCQueryAction.decodeReturnedKeys(JDBCQueryAction.java:188)
	at io.vertx.jdbcclient.impl.actions.JDBCQueryAction.decode(JDBCQueryAction.java:59)
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:69)
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:39)
	at io.vertx.ext.jdbc.impl.JDBCConnectionImpl.lambda$schedule$3(JDBCConnectionImpl.java:217)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:179)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:177)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 121
	at java.lang.String.checkBounds(String.java:385)
	at java.lang.String.<init>(String.java:462)
	at org.mariadb.jdbc.internal.com.read.Buffer.readStringLengthEncoded(Buffer.java:123)
	at org.mariadb.jdbc.internal.com.read.resultset.ColumnDefinition.getString(ColumnDefinition.java:227)
	at org.mariadb.jdbc.internal.com.read.resultset.ColumnDefinition.getName(ColumnDefinition.java:243)
	at org.mariadb.jdbc.MariaDbResultSetMetaData.getColumnLabel(MariaDbResultSetMetaData.java:154)
	at io.vertx.jdbcclient.impl.actions.JDBCQueryAction.decodeReturnedKeys(JDBCQueryAction.java:188)
	at io.vertx.jdbcclient.impl.actions.JDBCQueryAction.decode(JDBCQueryAction.java:59)
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:69)
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:39)
	at io.vertx.ext.jdbc.impl.JDBCConnectionImpl.lambda$schedule$3(JDBCConnectionImpl.java:217)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:179)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:177)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
I tried the same with the connection pooling provided by the MariaDB Java Client and by using C3P0 on top of the MariaDB Java Client but could not reproduce this kind of issues.

### Do you have a reproducer?

A reproducer can be found at https://github.com/riemenschneider/JDBCPoolUsingMariaDBDriverTest. The reproduced consists of three tests:
1. MariaDBConnectionPool: using the connection pooling provided by MariaDB Java Client for running 1000 prepared queries in parallel.
2. C3P0ConnectionPool: using C3P0 on top of the MariaDB Java Client for running 1000 prepared queries in parallel.
3. VertxConnectionPool: using JDBCPool from the Sql Client API (which defaults to C3P0) on top of the MariaDB Java Client for running a prepared query 100 times in parallel. This was enough to reproduce the issue on all machines I have tested with.

### Steps to reproduce

1. Clone the reproducer.
2. Run gradlew test in the root folder of the cloned reproducer.

### Extra

We experienced this issue with OpenJDK 64-Bit Server VM 1.8.0_272-b17 (Azul Systems, Inc. 25.272-b17) and Windows 10 as well as OpenJDK 64-Bit Server VM 11.0.9+11-LTS (Azul Systems, Inc. 11.0.9+11-LTS).

**Comment by riemenschneider** [comment]
I have added two more tests. One for the legacy JDBC Client API and one for the new Sql Client API in manual connection mode. From my point of view the new Sql Client API fails in managed as well as manual connection mode when executing prepared queries in parallel. The legacy JDBC Client API (as well as using connection pooling provided by MariaDB Java Client and C3P0 on top of MariaDB Java Client) does not show these kind of problems.

**Comment by riemenschneider** [comment]
I have instrumented some classes of the MariaDB Java Client in order to show additional debug output and it looks like the same Buffer is used by multiple tests executions running in parallel.
```
[vert.x-worker-thread-1] INFO org.mariadb.jdbc.internal.com.read.resultset.ColumnDefinition - org.mariadb.jdbc.internal.com.read.resultset.ColumnDefinition@c03d80a.getString(4)
[vert.x-worker-thread-1] INFO org.mariadb.jdbc.internal.com.read.Buffer - org.mariadb.jdbc.internal.com.read.Buffer@19b7de57.skipLengthEncodedBytes()
[vert.x-worker-thread-1] INFO org.mariadb.jdbc.internal.com.read.Buffer - org.mariadb.jdbc.internal.com.read.Buffer@19b7de57.skipLengthEncodedBytes()
[vert.x-worker-thread-4] INFO org.mariadb.jdbc.internal.com.read.resultset.ColumnDefinition - org.mariadb.jdbc.internal.com.read.resultset.ColumnDefinition@c03d80a.getString(4)
[vert.x-worker-thread-4] INFO org.mariadb.jdbc.internal.com.read.Buffer - org.mariadb.jdbc.internal.com.read.Buffer@19b7de57.skipLengthEncodedBytes()
[vert.x-worker-thread-4] INFO org.mariadb.jdbc.internal.com.read.Buffer - org.mariadb.jdbc.internal.com.read.Buffer@19b7de57.skipLengthEncodedBytes()
[vert.x-worker-thread-4] INFO org.mariadb.jdbc.internal.com.read.Buffer - org.mariadb.jdbc.internal.com.read.Buffer@19b7de57.skipLengthEncodedBytes()
[vert.x-worker-thread-4] INFO org.mariadb.jdbc.internal.com.read.Buffer - org.mariadb.jdbc.internal.com.read.Buffer@19b7de57.skipLengthEncodedBytes()
[vert.x-worker-thread-4] INFO org.mariadb.jdbc.internal.com.read.Buffer - org.mariadb.jdbc.internal.com.read.Buffer@19b7de57.readStringLengthEncoded(UTF-8)
[vert.x-worker-thread-4] INFO org.mariadb.jdbc.internal.com.read.Buffer - org.mariadb.jdbc.internal.com.read.Buffer@19b7de57.getLengthEncodedNumeric()
[vert.x-worker-thread-1] INFO org.mariadb.jdbc.internal.com.read.Buffer - org.mariadb.jdbc.internal.com.read.Buffer@19b7de57.skipLengthEncodedBytes()
[vert.x-worker-thread-1] INFO org.mariadb.jdbc.internal.com.read.Buffer - org.mariadb.jdbc.internal.com.read.Buffer@19b7de57.skipLengthEncodedBytes()
[vert.x-worker-thread-1] INFO org.mariadb.jdbc.internal.com.read.Buffer - org.mariadb.jdbc.internal.com.read.Buffer@19b7de57.readStringLengthEncoded(UTF-8)
[vert.x-worker-thread-1] INFO org.mariadb.jdbc.internal.com.read.Buffer - org.mariadb.jdbc.internal.com.read.Buffer@19b7de57.getLengthEncodedNumeric()
[vert.x-worker-thread-1] ERROR org.mariadb.jdbc.internal.com.read.resultset.ColumnDefinition - GOTCHA
java.lang.ArrayIndexOutOfBoundsException: Index 37 out of bounds for length 37
	at org.mariadb.jdbc.internal.com.read.Buffer.getLengthEncodedNumeric(Buffer.java:278)
	at org.mariadb.jdbc.internal.com.read.Buffer.readStringLengthEncoded(Buffer.java:127)
	at org.mariadb.jdbc.internal.com.read.resultset.ColumnDefinition.getString(ColumnDefinition.java:233)
	at org.mariadb.jdbc.internal.com.read.resultset.ColumnDefinition.getName(ColumnDefinition.java:254)
	at org.mariadb.jdbc.MariaDbResultSetMetaData.getColumnLabel(MariaDbResultSetMetaData.java:154)
	at io.vertx.jdbcclient.impl.actions.JDBCQueryAction.decodeReturnedKeys(JDBCQueryAction.java:188)
	at io.vertx.jdbcclient.impl.actions.JDBCQueryAction.decode(JDBCQueryAction.java:59)
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:69)
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:39)
	at io.vertx.ext.jdbc.impl.JDBCConnectionImpl.lambda$schedule$3(JDBCConnectionImpl.java:217)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:179)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:177)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by riemenschneider** [comment]
Looks like https://github.com/vert-x3/vertx-jdbc-client/pull/218 adds configuration support for disabling automatic key generation. This can be used as a **workaround** for this issue (at least in our scenario) since the exceptions only occur when creating a prepared query using the ``Statement.RETURN_GENERATED_KEYS`` option and processing the generated keys afterwards.

**Comment by riemenschneider** [comment]
I was finally able to track that issue down to an issue in MariaDB Connector/J (see https://jira.mariadb.org/browse/CONJ-873). Therefore this issue can be closed. The only remaining question is if there is already a release date for Vert.x 4.1.0 which would give us a workaround for the issue in MariaDB Connector/J.

**Comment by vietj** [comment]
we expect a first beta of 4.1 early May and a final release in June.

**Comment by vietj** [comment]
yes this looks like a concurrent utilisation

**Comment by riemenschneider** [comment]
I think we should close this issue since it is caused by concurrent usage of shared buffers in MariaDB Connector/J (see https://jira.mariadb.org/browse/CONJ-873) and we have a workaround (disabling automatic key generation) since Vert.x 4.1.0.
