### ISSUE TITLE
JDBCPool.query(...).execute() does not return the connection to the pool if the query is failing

### ISSUE THREAD

**Issue by riemenschneider** [vert-x3/vertx-jdbc-client#226]
### Version

4.2.0

### Context

I encountered an issue with respect to connection pooling when queries are failing. It looks like the connection is not returned to the connection pool in this case. As a result the pool might run out of connections when we have multiple failing queries.
The issue occurs when we are using the `query(...)` and `preparedQuery(...)` methods of `JDBCPool`:
```
  pool
    .query("SELECT FROM WHERE FOO BAR")
    .execute();
```
When executing the same query via the `withConnection(...)` method of `JDBCPool` we do not see such an issue (therefore using `withConnection(...)` instead of executing queries directly is a wokraround for this issue):
```
  pool
    .withConnection(conn -> conn
      .query("SELECT FROM WHERE FOO BAR")
      .execute());
```

### Do you have a reproducer?

I have a fork of the repository with an extended `JDBCPoolTest` containing tests for the issue as well as the workaround (see https://github.com/riemenschneider/vertx-jdbc-client).

### Steps to reproduce

1. Clone the reproducer.
2. Run `io.vertx.jdbcclient.JDBCPoolTest`.

**Comment by riemenschneider** [comment]
I have created pull request #227 which should fix this issue. Unfortunately some tests are failing with the following error
```
java.sql.SQLException: Access is denied: pom.xml
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.SessionData.getFile(Unknown Source)
	at org.hsqldb.SessionData.createBlobFromFile(Unknown Source)
	at org.hsqldb.FunctionCustom.getValue(Unknown Source)
	at org.hsqldb.FunctionSQL.getValue(Unknown Source)
	at org.hsqldb.StatementDML.getInsertData(Unknown Source)
	at org.hsqldb.StatementInsert.getResult(Unknown Source)
	at org.hsqldb.StatementDMQL.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.executeDirectStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.execute(Unknown Source)
	at io.vertx.ext.jdbc.JDBCClientTestBase.resetDb(JDBCClientTestBase.java:73)
	at io.vertx.jdbcclient.ClientTestBase.setUp(ClientTestBase.java:26)
	at io.vertx.jdbcclient.JDBCPoolCustomTypesTest.setUp(JDBCPoolCustomTypesTest.java:58)
```
which is (to the best of my knowledge) not connected to my fix.
