### ISSUE TITLE
JDBCpool setting setIdleTimeout is not valid

### ISSUE THREAD

**Issue by shenzhenMirren** [vert-x3/vertx-jdbc-client#238]
### Questions
This is the code that I created the JDBCpool
````
JDBCConnectOptions options = new JDBCConnectOptions();
options.setJdbcUrl("url");
options.setUser("user");
options.setPassword("pwd");
PoolOptions poolOptions = new PoolOptions().setMaxSize(50);
poolOptions.setIdleTimeout(1200);
JDBCPool jdbcPool = JDBCPool.pool(vertx, options, poolOptions);
````

Hello! I set idle timeout to 1200 seconds in the JDBCpool of vert.x 4.1.3. 
this setting is valid on Linux. It will recycle idle connections, 
but it is invalid on windows. It will not recycle idle connections,
will report the following errors:

```
com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 53,641,799 milliseconds ago. The last packet sent successfully to the server was 53,641,813 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[znh-creator-fat.jar:?]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[znh-creator-fat.jar:?]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[znh-creator-fat.jar:?]
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370) ~[znh-creator-fat.jar:?]
	at io.agroal.pool.wrapper.PreparedStatementWrapper.execute(PreparedStatementWrapper.java:299) ~[znh-creator-fat.jar:?]
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:71) ~[znh-creator-fat.jar:?]
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:39) ~[znh-creator-fat.jar:?]
	at io.vertx.ext.jdbc.impl.JDBCConnectionImpl.lambda$schedule$3(JDBCConnectionImpl.java:219) ~[znh-creator-fat.jar:?]
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159) ~[znh-creator-fat.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[znh-creator-fat.jar:?]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157) ~[znh-creator-fat.jar:?]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[znh-creator-fat.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_121]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [znh-creator-fat.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: The last packet successfully received from the server was 53,641,799 milliseconds ago. The last packet sent successfully to the server was 53,641,813 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_121]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[znh-creator-fat.jar:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[znh-creator-fat.jar:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[znh-creator-fat.jar:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[znh-creator-fat.jar:?]
	at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:550) ~[znh-creator-fat.jar:?]
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:605) ~[znh-creator-fat.jar:?]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:970) ~[znh-creator-fat.jar:?]
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:662) ~[znh-creator-fat.jar:?]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930) ~[znh-creator-fat.jar:?]
	... 13 more
Caused by: java.net.SocketException: Software caused connection abort: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:1.8.0_121]
	at java.net.SocketOutputStream.socketWrite(Unknown Source) ~[?:1.8.0_121]
	at java.net.SocketOutputStream.write(Unknown Source) ~[?:1.8.0_121]
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source) ~[?:1.8.0_121]
	at java.io.BufferedOutputStream.flush(Unknown Source) ~[?:1.8.0_121]
	at com.mysql.cj.protocol.a.SimplePacketSender.send(SimplePacketSender.java:55) ~[znh-creator-fat.jar:?]
	at com.mysql.cj.protocol.a.TimeTrackingPacketSender.send(TimeTrackingPacketSender.java:50) ~[znh-creator-fat.jar:?]
	at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:541) ~[znh-creator-fat.jar:?]
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:605) ~[znh-creator-fat.jar:?]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:970) ~[znh-creator-fat.jar:?]
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:662) ~[znh-creator-fat.jar:?]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930) ~[znh-creator-fat.jar:?]
	... 13 more

```

### Version
vert.x 4.1.3

### Extra
edition 	 Windows 10 professional
Version number 	 21H2
install date 	 ‎2020/‎5/‎16
Operating system build 	 19044.1202
experience 	 Windows Feature Experience Pack 120.2212.3030.0
Java 8 & Java 15

**Comment by shenzhenMirren** [comment]
This problem also exists in CentOS, that is, the connection pool does not recycle free connection

**Comment by vietj** [comment]
do you have a reproducer project ?

**Comment by shenzhenMirren** [comment]
Sorry, this is my problem. I don't have idle time for connection
