### ISSUE TITLE
IllegalArgumentException: Type:-101 is not a valid Types.java value. when using TIMESTAMP WITH TIME ZONE

### ISSUE THREAD

**Issue by klas3000** [vert-x3/vertx-jdbc-client#248]
### Version

4.2.0

### Context

using a column like this

```
created TIMESTAMP WITH TIME ZONE NOT NULL
```
I got this

```
java.lang.IllegalArgumentException: Type:-101 is not a valid Types.java value.
	at java.sql.JDBCType.valueOf(JDBCType.java:258)
	at io.vertx.ext.jdbc.impl.actions.JDBCTypeProvider.lambda$fromResult$1(JDBCTypeProvider.java:45)
	at io.vertx.jdbcclient.impl.actions.JDBCColumnDescriptor.<init>(JDBCColumnDescriptor.java:30)
	at io.vertx.jdbcclient.impl.actions.JDBCQueryAction.decodeResultSet(JDBCQueryAction.java:111)
	at io.vertx.jdbcclient.impl.actions.JDBCQueryAction.decode(JDBCQueryAction.java:51)
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:73)
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:39)
	at io.vertx.ext.jdbc.impl.JDBCConnectionImpl.lambda$schedule$3(JDBCConnectionImpl.java:219)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)

```

### Extra

(but, works "without time zone")

same problem with
x64\jdk-11.0.1\bin\java.exe and x64\jdk-8u191\bin\java.exe

if I use "TIMESTAMP WITH TIME ZONE" with raw java.sql.PreparedStatement "it works"

**Comment by klas3000** [comment]
see also https://groups.google.com/g/vertx/c/4MuvIOjXLc0/m/GbPdwz8PAgAJ

**Comment by tsegismont** [comment]
Can you share simplified SQL for creating/inserting data in the table? Thank you

**Comment by klas3000** [comment]
hmm...

I think this is still not working... just different exception...

```
    fun select() {
        pool.preparedQuery("SELECT id, name, created FROM my_table1 where name=?").execute(Tuple.of("john"))
            .onSuccess { rowset ->
                rowset.forEach { row ->
                    val name = row.getString("NAME")
                    println("Name: $name")
                    val time = row.get(OffsetDateTime::class.java, "CREATED")
                    println("Created: $time")
                }
            }.onFailure { it.printStackTrace() }
    }
```

result (vertx 4.2.5, oracle driver 21.4.0.0):
```
Name: john
[vert.x-eventloop-thread-0] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.time.OffsetDateTime (java.lang.String and java.time.OffsetDateTime are in module java.base of loader 'bootstrap')
	at io.vertx.sqlclient.Tuple.getOffsetDateTime(Tuple.java:572)
	at io.vertx.jdbcclient.impl.JDBCRow.get(JDBCRow.java:95)
	at io.vertx.sqlclient.Row.get(Row.java:721)
	at foo.ConsumerVerticle.select$lambda-4(HelloWorld.kt:49)
```

**Comment by tsegismont** [comment]
@klas3000 I've looked into this and, in fact, this PR has been superseded by #256 (also in 4.2.2).

So what you have to do is creating a custom decoder class, something like:

```java
  public static class CustomDecoder extends JDBCDecoderImpl {

    @Override
    protected Object decodeSpecificVendorType(SQLValueProvider valueProvider, JDBCColumnDescriptor descriptor) throws SQLException {
      Object value = valueProvider.apply(null);
      if (value instanceof TIMESTAMPTZ) {
        TIMESTAMPTZ timestamptz = (TIMESTAMPTZ) value;
        return timestamptz.toOffsetDateTime();
      }
      return super.decodeSpecificVendorType(valueProvider, descriptor);
    }
  }
```

And then [configure the JDBC client](https://vertx.io/docs/vertx-jdbc-client/java/#_data_types) to use it. You can either:

- put your custom class name in a `META-INF/services/io.vertx.ext.jdbc.spi.JDBCDecoder` file, or
- configure the datasource provider with `decoderCls` property:

```java
    options = new JDBCConnectOptions()
      .setJdbcUrl(jdbcUrl)
      .setUser(username)
      .setPassword(password);
    vertx = Vertx.vertx();
    JsonObject extraOptions = new JsonObject()
      .put("decoderCls", CustomDecoder.class.getName());
    DataSourceProvider provider = new AgroalCPDataSourceProvider(options, poolOptions()).init(extraOptions);
    client = JDBCPool.pool(vertx, provider);
```
