### ISSUE TITLE
Thread Blocked using MySql Connector/J

### ISSUE THREAD

**Issue by rennyahernandez** [vert-x3/vertx-jdbc-client#251]
### Version

vertx-rxjava2 4.1.2
jvm 8
hikaricp 4.0.3 
mysql-connector-java 8.0.16

### Context

I encountered a thread blocked warning when using mysql with ConnectorJ driver. The warning is: 

```
 WARN i.v.c.i.BlockedThreadChecker – Thread Thread[vert.x-worker-thread-9,5,main] has been blocked for 60824179 ms, time limit is 60000 ms
 io.vertx.core.VertxException: Thread blocked
 	at app//com.mysql.cj.jdbc.ha.ReplicationConnectionProxy.getCurrentConnection(ReplicationConnectionProxy.java:516)
 	at app//com.mysql.cj.jdbc.ha.ReplicationMySQLConnection.getCurrentConnection(ReplicationMySQLConnection.java:58)
 	at app//com.mysql.cj.jdbc.ha.ReplicationMySQLConnection.getActiveMySQLConnection(ReplicationMySQLConnection.java:53)
 	at app//com.mysql.cj.jdbc.ha.MultiHostMySQLConnection.getConnectionMutex(MultiHostMySQLConnection.java:646)
 	at app//com.mysql.cj.jdbc.ServerPreparedStatement.close(ServerPreparedStatement.java:268)
 	at jdk.internal.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
 	at java.base@11.0.10/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 	at java.base@11.0.10/java.lang.reflect.Method.invoke(Unknown Source)
 	at app//com.mysql.cj.jdbc.ha.MultiHostConnectionProxy$JdbcInterfaceProxy.invoke(MultiHostConnectionProxy.java:107)
 	at app//com.sun.proxy.$Proxy44.close(Unknown Source)
 	at app//com.zaxxer.hikari.pool.ProxyStatement.close(ProxyStatement.java:75)
 	at app//io.vertx.ext.jdbc.impl.actions.JDBCQuery.execute(JDBCQuery.java:71)
 	at app//io.vertx.ext.jdbc.impl.actions.JDBCQuery.execute(JDBCQuery.java:30)
 	at app//io.vertx.ext.jdbc.impl.JDBCConnectionImpl.lambda$schedule$3(JDBCConnectionImpl.java:219)
 	at app//io.vertx.ext.jdbc.impl.JDBCConnectionImpl$$Lambda$619/0x00000001008ea840.handle(Unknown Source)
 	at app//io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:160)
 	at app//io.vertx.core.impl.ContextImpl$$Lambda$196/0x00000001004b5c40.handle(Unknown Source)
 	at app//io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
 	at app//io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:158)
 	at app//io.vertx.core.impl.ContextImpl$$Lambda$180/0x000000010049b040.run(Unknown Source)
```

### Do you have a reproducer?
```
class Database @Inject constructor(
    private val jdbc: JDBCClient
) {
fun execute(sqlStatement: String): Single<UpdateResult> {
        return jdbc
            .rxGetConnection()
            .subscribeOn(Schedulers.io())
            .map {
                it
                    .setOptions(
                        SQLOptions()
                            .setReadOnly(false)
                            .setQueryTimeout(5)
                    )
            }
            .flatMap { sqlConnection ->
                sqlConnection
                    .rxUpdate(sqlStatement)
                    .doOnError {
                       //handle error
                      }
                    .doFinally {
                       sqlConnection
                          .rxClose()
                          .subscribe({}, {//error handling})
                }
        }
    }
}
```

**Comment by tsegismont** [comment]
This is not a bug. It seems the JDBC driver `getConnection` method has blocked the worker thread for more than 16 hours.

It seems the driver is configured to use the MySQL HA feature. Perhaps there's a problem in the configuration?

**Comment by rennyahernandez** [comment]
Hi @tsegismont. Thanks for your reply. 

Is it expected for the client to block a thread in case of a misconfiguration? The config values are: 

```
val dataSource = JsonObject().apply {
            put("connectionTimeout", 1000)
            put("prepStmtCacheSize", 250)
            put("prepStmtCacheSqlLimit", 8192)
            put("cachePrepStmts", true)
            put("useServerPrepStmts", true)
            put("maintainTimeStats", false)
            put("useUnbufferedIO", false)
            put("useReadAheadInput", false)
            put("maximumPoolSize", 10)
            put("socketTimeout", 10000) 
            put("allowReplicasDownConnections", true)
            put("readFromSourceWhenNoReplicas", true)
        }

        val config = JsonObject().apply {
            put("provider_class", "io.vertx.ext.jdbc.spi.impl.HikariCPDataSourceProvider")
            put("jdbcUrl", <someurl>)
            put("driverClassName", "com.mysql.cj.jdbc.Driver")
            put("username", config.username)
            put("password", config.password)
            put("datasource", dataSource)
        }

        return JDBCClient.createShared(vertx, config)

```

Thanks again for your help

**Comment by tsegismont** [comment]
@rennyahernandez I don't know if it is related to the JDBC driver configuration. It was a suggestion for investigation.

My point is this is not an issue with the Vert.x JDBC Client, but rather the MS SQL JDBC driver that is stuck in `getConnection` method.
