### ISSUE TITLE
JsonArray add causing NullPointerException with some JDBC drivers

### ISSUE THREAD

**Issue by cramertj** [vert-x3/vertx-jdbc-client#27]
Steps to reproduce:
1. Obtain a SQLConnection using the Microsoft SQL Server JDBC driver version 4.0
2. Run an UPDATE or DELETE statement with SQLConnection.updateWithParams or SQLConnection.update

The update will go through (changes in the database will be made), but the AsyncResult returned will have a true .failed(), with a .cause() of java.lang.NullPointerException. The full stack trace is below:

`java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at io.vertx.core.json.JsonArray.add(JsonArray.java:395)
	at io.vertx.ext.jdbc.impl.actions.JDBCUpdate.executeStatement(JDBCUpdate.java:53)
	at io.vertx.ext.jdbc.impl.actions.JDBCUpdate.executeStatement(JDBCUpdate.java:33)
	at io.vertx.ext.jdbc.impl.actions.AbstractJDBCStatement.execute(AbstractJDBCStatement.java:51)
	at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.handle(AbstractJDBCAction.java:48)
	at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.handle(AbstractJDBCAction.java:33)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$14(ContextImpl.java:279)
	at io.vertx.core.impl.ContextImpl$$Lambda$9/1844214132.run(Unknown Source)
	at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$161(OrderedExecutorFactory.java:91)
	at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor$$Lambda$1/475266352.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)`

**Comment by cramertj** [comment]
After cloning, I see that this issue has already been resolved by checking for null ResultSet, even though it was not fixed in my local copy pulled from Maven.
