### ISSUE TITLE
Unsupported access properties in SQL metadata java.sql.SQLException:Parameter metadata not available for the given statement

### ISSUE THREAD

**Issue by shenzhenMirren** [vert-x3/vertx-jdbc-client#294]
In version 4.3.5, the following code will have an error under the debug log output. 
This problem does not exist in 4.3.4. 
If I add generateSimpleParameterMetadata=true to the URL, I will not output this error

```
    JDBCConnectOptions options = new JDBCConnectOptions();
    options.setJdbcUrl("jdbc:mysql://127.0.0.1:3306/bible-pro-data-center?useUnicode=true&useSSL=false&serverTimezone=UTC");
    options.setUser("root");
    options.setPassword("root");
    options.setIdleTimeout(1200000);
    PoolOptions poolOptions = new PoolOptions().setMaxSize(30);
    Vertx vertx = Vertx.vertx();
    JDBCPool pool = JDBCPool.pool(vertx, options, poolOptions);

   String sql = "select * from users where id=?";
    Tuple tuple = Tuple.tuple().addString("test");
    pool.preparedQuery(sql).execute(tuple).onFailure(err -> {
      System.out.println(err);
    }).onSuccess(rows -> {
      for (Row row : rows) {
        System.out.println(row.toJson());
      }
    });

```

```
[DEBUG] [2022-12-06 09:45:23]  Unsupported access properties in SQL metadata
java.sql.SQLException: Parameter metadata not available for the given statement
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at com.mysql.cj.jdbc.MysqlParameterMetadata.checkAvailable(MysqlParameterMetadata.java:86) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at com.mysql.cj.jdbc.MysqlParameterMetadata.getParameterClassName(MysqlParameterMetadata.java:164) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at io.vertx.ext.jdbc.spi.JDBCColumnDescriptorProvider.lambda$null$8(JDBCColumnDescriptorProvider.java:63) ~[vertx-jdbc-client-4.3.5.jar:4.3.5]
	at io.vertx.jdbcclient.impl.actions.JDBCPropertyAccessor.lambda$create$0(JDBCPropertyAccessor.java:38) ~[vertx-jdbc-client-4.3.5.jar:4.3.5]
	at io.vertx.jdbcclient.impl.actions.JDBCColumnDescriptor.create(JDBCColumnDescriptor.java:73) ~[vertx-jdbc-client-4.3.5.jar:4.3.5]
	at io.vertx.ext.jdbc.spi.JDBCColumnDescriptorProvider.lambda$fromParameterMetaData$9(JDBCColumnDescriptorProvider.java:60) ~[vertx-jdbc-client-4.3.5.jar:4.3.5]
	at io.vertx.ext.jdbc.spi.impl.JDBCEncoderImpl.encode(JDBCEncoderImpl.java:51) ~[vertx-jdbc-client-4.3.5.jar:4.3.5]
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.fillStatement(JDBCPreparedQuery.java:142) ~[vertx-jdbc-client-4.3.5.jar:4.3.5]
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:63) ~[vertx-jdbc-client-4.3.5.jar:4.3.5]
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:44) ~[vertx-jdbc-client-4.3.5.jar:4.3.5]
	at io.vertx.ext.jdbc.impl.JDBCConnectionImpl.lambda$schedule$3(JDBCConnectionImpl.java:219) ~[vertx-jdbc-client-4.3.5.jar:4.3.5]
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137) ~[vertx-core-4.3.5.jar:4.3.5]
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264) ~[vertx-core-4.3.5.jar:4.3.5]
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135) ~[vertx-core-4.3.5.jar:4.3.5]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[vertx-core-4.3.5.jar:4.3.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.85.Final.jar:4.1.85.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[DEBUG] [2022-12-06 09:45:23]  Convert JDBC column [JDBCColumnDescriptor[columnName=(0), jdbcTypeWrapper=(JDBCTypeWrapper[vendorTypeNumber=(1111), vendorTypeName=(null), vendorTypeClass=(null), jdbcType=(OTHER)])]][java.lang.String]

```

**Comment by canglangX** [comment]
I ran into the same problem when using ojdbc8, the driver did not support this method

**Comment by tsegismont** [comment]
The exception is expected but we could do better as discussed in https://github.com/vert-x3/vertx-jdbc-client/issues/295#issuecomment-1361611022

I'll keep this issue open until we make a decision for enhancement

**Comment by tsegismont** [comment]
The exception is expected, if it's annoying, set the logger level to INFO for the `JDBCColumnDescriptor` class
