### ISSUE TITLE
More accurate error information:` Need to fetch more data from DB` or support More DataTypes

### ISSUE THREAD

**Issue by laglangyue** [vert-x3/vertx-jdbc-client#312]
#### Read me

Read this first before creating an issue:

- do not use this issue tracker to ask questions, instead use one of these [channels](https://vertx.io/community/). Questions will likely be closed without notice.
- you shall create a feature request only when it is general purpose enough.
- make sure that the feature is not already

#### Describe the feature
now, for db2-client,we don't support blob and clob. It will cause exception when I query them
```
java.lang.UnsupportedOperationException: Need to fetch more data from DB
	at io.vertx.db2client.impl.codec.SimpleQueryCommandCodec.decodeQuery(SimpleQueryCommandCodec.java:86)
	at io.vertx.db2client.impl.codec.QueryCommandBaseCodec.decodePayload(QueryCommandBaseCodec.java:69)
	at io.vertx.db2client.impl.codec.DB2Decoder.decodePayload(DB2Decoder.java:79)
	at io.vertx.db2client.impl.codec.DB2Decoder.decode(DB2Decoder.java:52)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
```

the message is confusing. Or we need support Clob and Blob

#### Use cases

A list of use cases this feature will enable and the value it creates.

#### Contribution

Who should implement this feature ? are you volunteering for implementing this feature or
do you know that is able and willing implement this feature ?

I am trying to use it and currently do not have the ability to modify the source code

**Comment by tsegismont** [comment]
Hi @laglangyue 

The stacktrace suggests the problem is  with the Reactive DB2 Client, not the JDBC Client. Can you please open the issue in the `vertx-sql-client` repo? Thank you
