### ISSUE TITLE
Documentation-Issue (maybe)

### ISSUE THREAD

**Issue by nikodemusP** [vert-x3/vertx-jdbc-client#321]
### Version

4.5.10

### Context

If you have a procedure within the postgre-sql database, the documentation says:

```
String sql = "{call new_customer(?, ?)}";
```

In this case the postgre-jdbc rejects the call with:

```
org.postgresql.util.PSQLException: ERROR: new_customer is a procedure
  Hint: To call a procedure, use CALL.
```

This is working:
String sql = "call new_customer(?, ?)";

**Comment by tsegismont** [comment]
Thanks for your report @nikodemusP 

We have tests working with the brackets, so I'm confused. Can you share a minimal yet complete reproducer ?

**Comment by nikodemusP** [comment]
Here is the repcase:

Tested on Ubuntu 24.04 and PostgreSQL 16

Procedure

```
create or replace procedure repcase( repcase_para OUT text) as $$ BEGIN repcase_para := 'Hallo'; END; $$ LANGUAGE PLPGSQL;
```

https://github.com/nikodemusP/Rep-Case-PostgreSQL

Output:

```
com.example.starter.RepCase 
org.postgresql.util.PSQLException: ERROR: repcase() is a procedure
  Hint: To call a procedure, use CALL.
  Position: 15
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2733)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2420)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:372)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:330)
        at org.postgresql.jdbc.PgPreparedStatement.getParameterMetaData(PgPreparedStatement.java:1761)
        at io.agroal.pool.wrapper.CallableStatementWrapper.getParameterMetaData(CallableStatementWrapper.java:1563)
        at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.fillStatement(JDBCPreparedQuery.java:135)
        at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:63)
```
And if you look into the log-file of PostgreSQL

```
2024-11-14 18:14:30.372 CET [16496] postgres@template1 ERROR:  repcase() is a procedure at character 15
2024-11-14 18:14:30.372 CET [16496] postgres@template1 HINT:  To call a procedure, use CALL.
2024-11-14 18:14:30.372 CET [16496] postgres@template1 STATEMENT:  select * from repcase($1) as result
```

If you remove the brackets, you will get the output "Hallo".
