### ISSUE TITLE
SQLFeatureNotSupportedException from Apache Phoenix JDBC Driver

### ISSUE THREAD

**Issue by aifgi** [vert-x3/vertx-jdbc-client#35]
I have following code working with Apache Phoenix (https://phoenix.apache.org):

    final JsonObject config = new JsonObject()
            .put("url", "jdbc:phoenix:localhost:2181:/hbase")
            .put("driver_class", "org.apache.phoenix.jdbc.PhoenixConnection")
    final JDBCClient client = JDBCClient.createShared(vertx(), config);
    jdbcClient.getConnection(res -> {
        if (res.succeeded()) {
            final SQLConnection connection = res.result();
            final JsonArray parameters = new JsonArray().put("param1", "value1");
            connection.updateWithParams(UPDATE_STATEMENT, parameters, res -> {
                if (res.failed()) {
                    LOG.error("Storing email message error", res.cause());
                }
            });
        }
    });

Its execution throws exception:

    java.sql.SQLFeatureNotSupportedException: null
	at    org.apache.phoenix.jdbc.PhoenixConnection.prepareStatement(PhoenixConnection.java:652) ~[phoenix-core-4.6.0-HBase-1.1.jar:4.6.0-HBase-1.1]
	at com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:507) ~[c3p0-0.9.5.1.jar:0.9.5.1]
	at io.vertx.ext.jdbc.impl.actions.JDBCUpdate.preparedStatement(JDBCUpdate.java:41) [vertx-jdbc-client-3.1.0.jar:na]
	at io.vertx.ext.jdbc.impl.actions.AbstractJDBCStatement.execute(AbstractJDBCStatement.java:48) [vertx-jdbc-client-3.1.0.jar:na]
	at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.handle(AbstractJDBCAction.java:48) [vertx-jdbc-client-3.1.0.jar:na]
	at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.handle(AbstractJDBCAction.java:33) [vertx-jdbc-client-3.1.0.jar:na]

It occurs because org.apache.phoenix.jdbc.PhoenixConnection doesn't support prepareStatement(String sql, int autoGeneratedKeys) method:

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

**Comment by cescoffier** [comment]
The Phoenix JDBC support is not complete. Phoenix only supports prepared statements without the set of column names.

**Comment by cescoffier** [comment]
For information, we are discussing with Phoenix to see what would be the best solution.

**Comment by cescoffier** [comment]
See https://issues.apache.org/jira/browse/PHOENIX-2453

**Comment by cescoffier** [comment]
Close this ticket, as it is handled by Phoenix.
