### ISSUE TITLE
vertx-jdbc-client Oracle 12c - operation not allowed

### ISSUE THREAD

**Issue by JSchering** [vert-x3/vertx-jdbc-client#46]
The vert.x jdbc client is throwing a "SQLException: operation not allowed" when performing an update on an Oracle 12c database using the vertx-jdbc-client 3.2.1. When performing an updateWithParams or update and passing in a simple update statement it fails with the following error:

java.lang.RuntimeException: java.sql.SQLException: operation not allowed
at com.sample.verticle.MyVerticle.lambda$8(MyVerticle.java:192)
at com.sample.verticle.MyVerticle$$Lambda$43/984091703.handle(Unknown Source)
at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.lambda$null$8(AbstractJDBCAction.java:65)
at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction$$Lambda$41/2139817074.handle(Unknown Source)
at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(ContextImpl.java:335)
at io.vertx.core.impl.ContextImpl$$Lambda$23/378909131.run(Unknown Source)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: operation not allowed
at oracle.jdbc.driver.OracleStatement.getGeneratedKeys(OracleStatement.java:5487)
at oracle.jdbc.driver.OracleStatementWrapper.getGeneratedKeys(OracleStatementWrapper.java:380)
at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.getGeneratedKeys(NewProxyPreparedStatement.java:2570)
at io.vertx.ext.jdbc.impl.actions.JDBCUpdate.execute(JDBCUpdate.java:55)
at io.vertx.ext.jdbc.impl.actions.JDBCUpdate.execute(JDBCUpdate.java:35)
at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.handle(AbstractJDBCAction.java:52)
at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.lambda$execute$10(AbstractJDBCAction.java:68)
at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction$$Lambda$39/1411764370.handle(Unknown Source)
at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(ContextImpl.java:335)
at io.vertx.core.impl.ContextImpl$$Lambda$23/378909131.run(Unknown Source)
at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$265(OrderedExecutorFactory.java:91)
at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor$$Lambda$20/988705146.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
... 1 mo

Here's what I'm doing:
```java
String sql = "update Whisky w set w.name='AAAAAAA' where w.id = ?"; 
    JsonArray params = new JsonArray().add(1); 
    this.client.getConnection(conn -> { 
    if (conn.succeeded()) { 
        SQLConnection connection = conn.result(); 
        connection.updateWithParams(sql, params, query -> { 
            if (query.succeeded()) { 
                System.out.println("Updated row"); 
            } 
            else { 
                throw new RuntimeException(query.cause()); 
        } 
        connection.close();
 }); 
} 
}); 
````
I posted this as a question here:
https://groups.google.com/forum/#!topic/vertx/dq7yTgEECAE

**Comment by JSchering** [comment]
Changing the code to use connection.execute. works around the issue, but you can no longer use prepared statements.

**Comment by rozzamozza** [comment]
The fix does not work in Oracle for the following type of sql insert:

insert into merchant (merchant_id,version,json,merchant_network_id,modified_date)
(select ?,?,?,?,? from merchant where merchant_id = ? having count(*) = 0), 

This is a typical type of command for part of doing an upsert.
You get 
java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

due to calling of:
     conn.prepareStatement(this.sql, returKeys?1:2);

**Comment by rozzamozza** [comment]
Just because you are doing an insert does not mean you want to call generate keys. A large number of data models do not rely on Database generated keys. They rely on natural keys of the data inserted (to stop duplicate etc)
