### ISSUE TITLE
Shared JDBCClient deadlock

### ISSUE THREAD

**Issue by rozzamozza** [vert-x3/vertx-jdbc-client#69]
io.vertx.core.VertxException: Thread blocked
 at io.vertx.ext.jdbc.impl.JDBCClientImpl.removeFromMap(JDBCClientImpl.java:158)
 at io.vertx.ext.jdbc.impl.JDBCClientImpl.lambda$lookupHolder$2(JDBCClientImpl.java:147)
 at io.vertx.ext.jdbc.impl.JDBCClientImpl$$Lambda$45/32529837.run(Unknown Source)
 at io.vertx.ext.jdbc.impl.JDBCClientImpl$DataSourceHolder.close(JDBCClientImpl.java:270)
 at io.vertx.ext.jdbc.impl.JDBCClientImpl.close(JDBCClientImpl.java:99)
 at ....database.schema.DatabaseClient.close(DatabaseClient.java:89)
 at ....status.service.StatusVerticle.lambda$createDatabase$4(StatusVerticle.java:72)
 at ....status.service.StatusVerticle$$Lambda$48/885304449.handle(Unknown Source)
 at ....status.persist.DatabaseStatusStore.lambda$null$12(DatabaseStatusStore.java:57)
 at ....status.persist.DatabaseStatusStore$$Lambda$97/2065785391.handle(Unknown Source)
 at ....util.futures.FutureChainImpl.lambda$completeOn$21(FutureChainImpl.java:381)
 at ....util.futures.FutureChainImpl$$Lambda$38/342198178.accept(Unknown Source)
 at ....util.futures.FutureChainImpl.lambda$notifyAllDependents$1(FutureChainImpl.java:65)
 at ....util.futures.FutureChainImpl$$Lambda$3/511717113.accept(Unknown Source)
 at java.lang.Iterable.forEach(Iterable.java:75)
 at ....util.futures.FutureChainImpl.notifyAllDependents(FutureChainImpl.java:65)
 at ....util.futures.FutureChainImpl.lambda$initialise$0(FutureChainImpl.java:58)
 at ....util.futures.FutureChainImpl$$Lambda$2/370440646.handle(Unknown Source)
 at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:158)
 at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:111)
 at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:135)
 at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:23)
 at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:158)
 at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:111)
 at ....status.persist.DatabaseStatusStore.lambda$null$16(DatabaseStatusStore.java:128)
 at ....status.persist.DatabaseStatusStore$$Lambda$121/1502216974.handle(Unknown Source)
 at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:158)
 at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:111)
 at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:135)
 at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:23)
 at ....util.DatabaseUtil.lambda$closeHandlerWithResult$26(DatabaseUtil.java:57)
 at ....util.DatabaseUtil$$Lambda$118/376501643.handle(Unknown Source)
 at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:158)
 at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
 at io.vertx.core.impl.ContextImpl.lambda$null$1(ContextImpl.java:315)
 at io.vertx.core.impl.ContextImpl$$Lambda$76/485234115.handle(Unknown Source)
 at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:359)
 at io.vertx.core.impl.ContextImpl$$Lambda$34/843710487.run(Unknown Source)
 at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:393)
 at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
 at java.lang.Thread.run(Thread.java:745)
 
 Aug 25, 2016 10:00:32 AM io.vertx.core.impl.BlockedThreadChecker
 WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 160447 ms, time limit is 2000
 io.vertx.core.VertxException: Thread blocked
 at io.vertx.ext.jdbc.impl.JDBCClientImpl$DataSourceHolder.incRefCount(JDBCClientImpl.java:240)
 at io.vertx.ext.jdbc.impl.JDBCClientImpl.lookupHolder(JDBCClientImpl.java:150)
 at io.vertx.ext.jdbc.impl.JDBCClientImpl.<init>(JDBCClientImpl.java:82)
 at io.vertx.ext.jdbc.JDBCClient.createShared(JDBCClient.java:72)
 at ....database.schema.DatabaseClient.<init>(DatabaseClient.java:53)
 at ....tokeniser.service.verticle.TokeniserVerticle.createDatabase(TokeniserVerticle.java:103)
 at ....tokeniser.service.verticle.TokeniserVerticle.start(TokeniserVerticle.java:71)
 at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434)
 at io.vertx.core.impl.DeploymentManager$$Lambda$33/1104422581.handle(Unknown Source)
 at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:359)
 at io.vertx.core.impl.ContextImpl$$Lambda$34/843710487.run(Unknown Source)
 at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:393)
 at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
 at java.lang.Thread.run(Thread.java:745)

**Comment by vietj** [comment]
hi, can you provide more details like a thread dump ?

**Comment by vietj** [comment]
info : 

first trace, locks on:
- DataSourceHolder (close)
- vertx instance (removeFromMap)

second trace, locks on:
- vertx (lookupHolder)
- DataSourceHolder (incRefCount)

**Comment by vietj** [comment]
the obvious fix is to acquire lock in the same order in both close and create

**Comment by vietj** [comment]
```
  @Test
  public void testFoo() throws Exception {
    JsonObject config = config();
    int num = 2;
    int iter = 50;
    AtomicInteger count = new AtomicInteger();
    List<Thread> threads = new ArrayList<>();
    for (int i = 0;i < num;i++) {
      Thread t = new Thread() {
        @Override
        public void run() {
          for (int i = 0;i < iter;i++) {
            count.incrementAndGet();
            JDBCClient client = JDBCClient.createShared(vertx, config);
            client.close();
          }
        }
      };
      threads.add(t);
    }
    for (Thread t : threads) {
      t.start();
    }
    while (count.get() < num * iter) {
      System.out.println(count.get());
      Thread.sleep(1000);
    }
    for (Thread t : threads) {
      t.join();
    }
  }
```

seems to reproduce it easily

**Comment by vietj** [comment]
with this dump:

```
"Thread-6" #20 prio=5 os_prio=31 tid=0x00007f933d83f800 nid=0x6603 waiting for monitor entry [0x0000700001df0000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at io.vertx.ext.jdbc.impl.JDBCClientImpl$DataSourceHolder.incRefCount(JDBCClientImpl.java:240)
	- waiting to lock <0x00000007a73481a0> (a io.vertx.ext.jdbc.impl.JDBCClientImpl$DataSourceHolder)
	at io.vertx.ext.jdbc.impl.JDBCClientImpl.lookupHolder(JDBCClientImpl.java:150)
	- locked <0x00000007ab038ae8> (a io.vertx.core.impl.VertxImpl)
	at io.vertx.ext.jdbc.impl.JDBCClientImpl.<init>(JDBCClientImpl.java:82)
	at io.vertx.ext.jdbc.JDBCClient.createShared(JDBCClient.java:82)
	at io.vertx.ext.jdbc.SharedDeadlockTest$1.run(SharedDeadlockTest.java:28)
"Thread-5" #19 prio=5 os_prio=31 tid=0x00007f933d83e800 nid=0x6403 waiting for monitor entry [0x0000700001ced000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at io.vertx.ext.jdbc.impl.JDBCClientImpl.removeFromMap(JDBCClientImpl.java:158)
	- waiting to lock <0x00000007ab038ae8> (a io.vertx.core.impl.VertxImpl)
	at io.vertx.ext.jdbc.impl.JDBCClientImpl.lambda$lookupHolder$2(JDBCClientImpl.java:147)
	at io.vertx.ext.jdbc.impl.JDBCClientImpl$$Lambda$34/1985106327.run(Unknown Source)
	at io.vertx.ext.jdbc.impl.JDBCClientImpl$DataSourceHolder.close(JDBCClientImpl.java:270)
	- locked <0x00000007a73481a0> (a io.vertx.ext.jdbc.impl.JDBCClientImpl$DataSourceHolder)
	at io.vertx.ext.jdbc.impl.JDBCClientImpl.close(JDBCClientImpl.java:99)
	at io.vertx.ext.jdbc.SharedDeadlockTest$1.run(SharedDeadlockTest.java:29)
```

**Comment by vietj** [comment]
will have a look at the fix
