### ISSUE TITLE
java.lang.AbstractMethodError: oracle.sql.CLOB.free() on old Oracle JDBC Driver

### ISSUE THREAD

**Issue by mannluong** [vert-x3/vertx-jdbc-client#71]
### Version

* vert.x core: 3.3.2
* vert.x jdbc-client: 3.3.2
* jdbc driver: 9.0.2.0.0
* RDBMS: Oracle

### General info

* What is your jdbc driver
oracle.jdbc.driver.OracleDriver
* What is your RDBMS server
Oracle
* What is your connection string (no user/passwords please!)
dbc:oracle:thin:@myserver:1521:db
### Context

I encountered an exception which looks suspicious while calling Oracle Stored Proc
{ call package_name.get_data(?, ?) } where first parameter is input Clob and second parameter is output.
the oracle jdbc driver was compiled against jdk 5 or lower (the interface java.sql.Clob does not have free method)

java.lang.AbstractMethodError: oracle.sql.CLOB.free()V
	at io.vertx.ext.jdbc.impl.actions.JDBCStatementHelper.convertSqlValue(JDBCStatementHelper.java:206)
	at io.vertx.ext.jdbc.impl.actions.JDBCCallable.convertOutputs(JDBCCallable.java:92)
	at io.vertx.ext.jdbc.impl.actions.JDBCCallable.execute(JDBCCallable.java:70)
	at io.vertx.ext.jdbc.impl.actions.JDBCCallable.execute(JDBCCallable.java:30)
	at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.handle(AbstractJDBCAction.java:55)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:303)
	at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$0(OrderedExecutorFactory.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

### Do you have a reproducer?

* Link to github project/gist

### Steps to reproduce

Similar bug can be found here
https://netbeans.org/bugzilla/show_bug.cgi?id=209834

client.getConnection(conn -> {
     connection.callWithParams(STORED_PROC, new JsonArray().add(requestJson), new      JsonArray().addNull().add("CLOB"), res -> {
     
}
}

**Comment by mannluong** [comment]
The defect is applicable for both Blob and Clob.

**Comment by pmlopes** [comment]
The defect will apply to all drivers complied for JDK5 isn't there any more up-to-date driver? It would feel more reasonable than wrap all blog/clob new JDBC api's with a try catch? WDYT?

**Comment by mannluong** [comment]
Thanks FYI Paulo, unfortunately the old version of Orcle v9.x does not work with the new driver JDBC Driver. 
Try/Catch for non-existent method is no ideal. 
Possible solutions:
1) Java reflection can be used to check to see whether the Clob/Blob object has the free method 

    public static boolean isExistedMethod(Object clobOrBlob, String methodName) {
        return Arrays.stream(obj.getClass().getMethods()).anyMatch(t->t.getName().equals(methodName));
    }

2) Possibly check http://stackoverflow.com/questions/4960487/how-can-i-determine-whether-a-jdbc-driver-is-type-4

**Comment by pmlopes** [comment]
@mannluong would you mind to check if the PR #72 fixes your issue with your DB? so we can merge and close this issue.

**Comment by mannluong** [comment]
@pmlopes the PR #72 fixes this issue. 
Thanks
